.TH "/home/dlebauer/dev/biocro/src/AuxwillowGro.h" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dlebauer/dev/biocro/src/AuxwillowGro.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAXLAY\fP   50 /* Maximum number of layers */"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBET_Str\fP \fBc3EvapoTrans\fP (double Rad, double Itot, double Airtemperature, double RH, double WindSpeed, double LeafAreaIndex, double CanopyHeight, double vcmax2, double jmax2, double Rd2, double b02, double b12, double Catm2, double O2, double theta2)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MAXLAY   50 /* Maximum number of layers */"

.SH "Function Documentation"
.PP 
.SS "struct \fBET_Str\fP c3EvapoTrans (doubleRad, doubleItot, doubleAirtemperature, doubleRH, doubleWindSpeed, doubleLeafAreaIndex, doubleCanopyHeight, doublevcmax2, doublejmax2, doubleRd2, doubleb02, doubleb12, doubleCatm2, doubleO2, doubletheta2)"

.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
