.TH "BioCroToCropcentParms" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BioCroToCropcentParms \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBstructometaSLOPE\fP"
.br
.ti -1c
.RI "double \fBstructometaINTERCEP\fP"
.br
.ti -1c
.RI "double \fBsurfacedamrN\fP"
.br
.ti -1c
.RI "double \fBsurfacedamrP\fP"
.br
.ti -1c
.RI "double \fBsurfacedamrS\fP"
.br
.ti -1c
.RI "double \fBsurfacedamrK\fP"
.br
.ti -1c
.RI "double \fBsoildamrN\fP"
.br
.ti -1c
.RI "double \fBsoildamrP\fP"
.br
.ti -1c
.RI "double \fBsoildamrS\fP"
.br
.ti -1c
.RI "double \fBsoildamrK\fP"
.br
.ti -1c
.RI "double \fBmindamrN\fP"
.br
.ti -1c
.RI "double \fBmindamrP\fP"
.br
.ti -1c
.RI "double \fBmindamrS\fP"
.br
.ti -1c
.RI "double \fBmindamrK\fP"
.br
.ti -1c
.RI "double \fBpabres\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double mindamrK"

.SS "double mindamrN"

.SS "double mindamrP"

.SS "double mindamrS"

.SS "double pabres"

.SS "double soildamrK"

.SS "double soildamrN"

.SS "double soildamrP"

.SS "double soildamrS"

.SS "double structometaINTERCEP"

.SS "double structometaSLOPE"

.SS "double surfacedamrK"

.SS "double surfacedamrN"

.SS "double surfacedamrP"

.SS "double surfacedamrS"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
