.TH "/home/dlebauer/dev/biocro/src/c3CanA.c" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dlebauer/dev/biocro/src/c3CanA.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <R\&.h>\fP
.br
\fC#include <Rinternals\&.h>\fP
.br
\fC#include <Rmath\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'c4photo\&.h'\fP
.br
\fC#include 'c3photo\&.h'\fP
.br
\fC#include 'AuxBioCro\&.h'\fP
.br
\fC#include 'CanA\&.h'\fP
.br
\fC#include 'c3CanA\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "SEXP \fBc3CanA\fP (SEXP Lai, SEXP Doy, SEXP HR, SEXP SOLAR, SEXP TEMP, SEXP ReH, SEXP windspeed, SEXP LAT, SEXP NLAYERS, SEXP PHOTOPS, SEXP KD, SEXP HEIGHTF, SEXP LNPS, SEXP STOMATAWS, SEXP WS)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "SEXP c3CanA (SEXPLai, SEXPDoy, SEXPHR, SEXPSOLAR, SEXPTEMP, SEXPReH, SEXPwindspeed, SEXPLAT, SEXPNLAYERS, SEXPPHOTOPS, SEXPKD, SEXPHEIGHTF, SEXPLNPS, SEXPSTOMATAWS, SEXPWS)"

.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
