.TH "c4_str" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
c4_str \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <c4photo\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBAssim\fP"
.br
.ti -1c
.RI "double \fBGs\fP"
.br
.ti -1c
.RI "double \fBCi\fP"
.br
.ti -1c
.RI "double \fBGrossAssim\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double Assim"

.SS "double Ci"

.SS "double GrossAssim"

.SS "double Gs"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
