.TH "/home/dlebauer/dev/biocro/src/caneGro.c" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dlebauer/dev/biocro/src/caneGro.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <R\&.h>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <Rmath\&.h>\fP
.br
\fC#include <Rinternals\&.h>\fP
.br
\fC#include 'AuxBioCro\&.h'\fP
.br
\fC#include 'Century\&.h'\fP
.br
\fC#include 'BioCro\&.h'\fP
.br
\fC#include 'AuxcaneGro\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "SEXP \fBcaneGro\fP (SEXP LAT, SEXP DOY, SEXP HR, SEXP SOLAR, SEXP TEMP, SEXP RH, SEXP WINDSPEED, SEXP PRECIP, SEXP KD, SEXP CHILHF, SEXP NLAYERS, SEXP RHIZOME, SEXP IRTL, SEXP SENCOEFS, SEXP TIMESTEP, SEXP VECSIZE, SEXP SPLEAF, SEXP SPD, SEXP DBPCOEFS, SEXP THERMALP, SEXP VMAX, SEXP ALPHA, SEXP KPARM, SEXP THETA, SEXP BETA, SEXP RD, SEXP CATM, SEXP B0, SEXP B1, SEXP WS, SEXP SOILCOEFS, SEXP ILEAFN, SEXP KLN, SEXP VMAXB1, SEXP ALPHAB1, SEXP MRESP, SEXP SOILTYPE, SEXP WSFUN, SEXP CENTCOEFS, SEXP CENTTIMESTEP, SEXP CENTKS, SEXP SOILLAYERS, SEXP SOILDEPTHS, SEXP CWS, SEXP HYDRDIST, SEXP SECS, SEXP KPLN, SEXP LNB0, SEXP LNB1, SEXP LNFUN, SEXP SUGARCOEFS, SEXP UPPERTEMP, SEXP LOWERTEMP, SEXP MAXLN, SEXP MINLN, SEXP DAYMAXLN, SEXP LEAFTURNOVER, SEXP ROOTTURNOVER, SEXP LEAFREMOBILIZE, SEXP OPTIONTOCALCULATEROOTDEPTH, SEXP ROOTFRONTVELOCITY, SEXP NNITROP, SEXP IRRIG, SEXP FROSTP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "SEXP caneGro (SEXPLAT, SEXPDOY, SEXPHR, SEXPSOLAR, SEXPTEMP, SEXPRH, SEXPWINDSPEED, SEXPPRECIP, SEXPKD, SEXPCHILHF, SEXPNLAYERS, SEXPRHIZOME, SEXPIRTL, SEXPSENCOEFS, SEXPTIMESTEP, SEXPVECSIZE, SEXPSPLEAF, SEXPSPD, SEXPDBPCOEFS, SEXPTHERMALP, SEXPVMAX, SEXPALPHA, SEXPKPARM, SEXPTHETA, SEXPBETA, SEXPRD, SEXPCATM, SEXPB0, SEXPB1, SEXPWS, SEXPSOILCOEFS, SEXPILEAFN, SEXPKLN, SEXPVMAXB1, SEXPALPHAB1, SEXPMRESP, SEXPSOILTYPE, SEXPWSFUN, SEXPCENTCOEFS, SEXPCENTTIMESTEP, SEXPCENTKS, SEXPSOILLAYERS, SEXPSOILDEPTHS, SEXPCWS, SEXPHYDRDIST, SEXPSECS, SEXPKPLN, SEXPLNB0, SEXPLNB1, SEXPLNFUN, SEXPSUGARCOEFS, SEXPUPPERTEMP, SEXPLOWERTEMP, SEXPMAXLN, SEXPMINLN, SEXPDAYMAXLN, SEXPLEAFTURNOVER, SEXPROOTTURNOVER, SEXPLEAFREMOBILIZE, SEXPOPTIONTOCALCULATEROOTDEPTH, SEXPROOTFRONTVELOCITY, SEXPNNITROP, SEXPIRRIG, SEXPFROSTP)"

.PP
\fBParameters:\fP
.RS 4
\fISUGARCOEFS\fP 
.PP
 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
