.TH "canopyparms" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
canopyparms \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBkN\fP"
.br
.ti -1c
.RI "double \fBSLA\fP"
.br
.ti -1c
.RI "double \fBremobFac\fP"
.br
.ti -1c
.RI "double \fBleafNsen\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double kN"

.SS "double leafNsen"

.SS "double remobFac"

.SS "double SLA"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
