.TH "canopyLeaf" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
canopyLeaf \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <c3canopy\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBLAI\fP"
.br
.ti -1c
.RI "double \fBpLeafsun\fP"
.br
.ti -1c
.RI "double \fBpLeafshade\fP"
.br
.ti -1c
.RI "double \fBheightf\fP"
.br
.ti -1c
.RI "double \fBLeafN\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double heightf"

.SS "double LAI"

.SS "double LeafN"

.SS "double pLeafshade"

.SS "double pLeafsun"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
