.TH "canopy" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
canopy \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <c3canopy\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBNlayers\fP"
.br
.ti -1c
.RI "double \fBIdirtop\fP"
.br
.ti -1c
.RI "double \fBIdifftop\fP"
.br
.ti -1c
.RI "double \fBCosZenithAngle\fP"
.br
.ti -1c
.RI "double \fBLAItotal\fP"
.br
.ti -1c
.RI "struct \fBcanopyEnv\fP * \fBENV\fP"
.br
.ti -1c
.RI "struct \fBcanopyLeaf\fP * \fBLeaf\fP"
.br
.ti -1c
.RI "struct \fBcanopyoutput\fP * \fBOUT\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double CosZenithAngle"

.SS "struct \fBcanopyEnv\fP* ENV"

.SS "double Idifftop"

.SS "double Idirtop"

.SS "double LAItotal"

.SS "struct \fBcanopyLeaf\fP* Leaf"

.SS "int Nlayers"

.SS "struct \fBcanopyoutput\fP* OUT"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
