.TH "canopyoutput" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
canopyoutput \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <c3canopy\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBsunlittemp\fP"
.br
.ti -1c
.RI "double \fBshadedtemp\fP"
.br
.ti -1c
.RI "double \fBTotalAnet\fP"
.br
.ti -1c
.RI "double \fBTotalAgross\fP"
.br
.ti -1c
.RI "double \fBTotalTrans\fP"
.br
.ti -1c
.RI "double \fBshadedAnet\fP"
.br
.ti -1c
.RI "double \fBshadedAgross\fP"
.br
.ti -1c
.RI "double \fBsunlitAnet\fP"
.br
.ti -1c
.RI "double \fBsunlitAgross\fP"
.br
.ti -1c
.RI "double \fBshadedTemp\fP"
.br
.ti -1c
.RI "double \fBsunlitTemp\fP"
.br
.ti -1c
.RI "double \fBshadedTranspiration\fP"
.br
.ti -1c
.RI "double \fBsunlitTranspiration\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double shadedAgross"

.SS "double shadedAnet"

.SS "double shadedtemp"

.SS "double shadedTemp"

.SS "double shadedTranspiration"

.SS "double sunlitAgross"

.SS "double sunlitAnet"

.SS "double sunlittemp"

.SS "double sunlitTemp"

.SS "double sunlitTranspiration"

.SS "double TotalAgross"

.SS "double TotalAnet"

.SS "double TotalTrans"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
