.TH "cropcentlayer" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cropcentlayer \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBstrucc1\fP \fBstrucc1\fP"
.br
.ti -1c
.RI "struct \fBstrucc2\fP \fBstrucc2\fP"
.br
.ti -1c
.RI "struct \fBmetabc1\fP \fBmetabc1\fP"
.br
.ti -1c
.RI "struct \fBmetabc2\fP \fBmetabc2\fP"
.br
.ti -1c
.RI "struct \fBsom1c1\fP \fBsom1c1\fP"
.br
.ti -1c
.RI "struct \fBsom1c2\fP \fBsom1c2\fP"
.br
.ti -1c
.RI "struct \fBsom2c1\fP \fBsom2c1\fP"
.br
.ti -1c
.RI "struct \fBsom2c2\fP \fBsom2c2\fP"
.br
.ti -1c
.RI "struct \fBsom3c\fP \fBsom3c\fP"
.br
.ti -1c
.RI "struct \fBwood1\fP \fBwood1\fP"
.br
.ti -1c
.RI "struct \fBwood2\fP \fBwood2\fP"
.br
.ti -1c
.RI "struct \fBwood3\fP \fBwood3\fP"
.br
.ti -1c
.RI "struct \fBcropcentEnvironment\fP \fBENV\fP"
.br
.ti -1c
.RI "struct \fBBioCroToCropcentParms\fP \fBBcroTOCentParms\fP"
.br
.ti -1c
.RI "struct \fBsoilprofile\fP \fBsoilprofile\fP"
.br
.ti -1c
.RI "struct \fBsiteparameters\fP \fBsitepar\fP"
.br
.ti -1c
.RI "struct \fBSoilEmissions\fP \fBEmission\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "struct \fBBioCroToCropcentParms\fP BcroTOCentParms"

.SS "struct \fBSoilEmissions\fP Emission"

.SS "struct \fBcropcentEnvironment\fP ENV"

.SS "struct \fBmetabc1\fP \fBmetabc1\fP"

.SS "struct \fBmetabc2\fP \fBmetabc2\fP"

.SS "struct \fBsiteparameters\fP sitepar"

.SS "struct \fBsoilprofile\fP \fBsoilprofile\fP"

.SS "struct \fBsom1c1\fP \fBsom1c1\fP"

.SS "struct \fBsom1c2\fP \fBsom1c2\fP"

.SS "struct \fBsom2c1\fP \fBsom2c1\fP"

.SS "struct \fBsom2c2\fP \fBsom2c2\fP"

.SS "struct \fBsom3c\fP \fBsom3c\fP"

.SS "struct \fBstrucc1\fP \fBstrucc1\fP"

.SS "struct \fBstrucc2\fP \fBstrucc2\fP"

.SS "struct \fBwood1\fP \fBwood1\fP"

.SS "struct \fBwood2\fP \fBwood2\fP"

.SS "struct \fBwood3\fP \fBwood3\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
