.TH "cropcentEnvironment" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cropcentEnvironment \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBminN\fP"
.br
.ti -1c
.RI "double \fBminP\fP"
.br
.ti -1c
.RI "double \fBminS\fP"
.br
.ti -1c
.RI "double \fBminK\fP"
.br
.ti -1c
.RI "double \fBnewminN\fP"
.br
.ti -1c
.RI "double \fBnewminP\fP"
.br
.ti -1c
.RI "double \fBnewminS\fP"
.br
.ti -1c
.RI "double \fBnewminK\fP"
.br
.ti -1c
.RI "double \fBammonium\fP"
.br
.ti -1c
.RI "double \fBsurfaceTEMP\fP"
.br
.ti -1c
.RI "double \fBsoilTEMP\fP"
.br
.ti -1c
.RI "double \fBsurfaceRELWC\fP"
.br
.ti -1c
.RI "double \fBsoilRELWC\fP"
.br
.ti -1c
.RI "double \fBPET\fP"
.br
.ti -1c
.RI "double \fBAWC\fP"
.br
.ti -1c
.RI "double \fBleachedWATER\fP"
.br
.ti -1c
.RI "double \fBpH\fP"
.br
.ti -1c
.RI "double \fBsoilrad\fP"
.br
.ti -1c
.RI "double \fBdrainage\fP"
.br
.ti -1c
.RI "double \fBnit_amt\fP"
.br
.ti -1c
.RI "struct \fBSoilTexture\fP \fBSOILTEX\fP"
.br
.ti -1c
.RI "struct \fBErosionParms\fP \fBEROSION\fP"
.br
.ti -1c
.RI "struct \fBOrgLeachParms\fP \fBORGLECH\fP"
.br
.ti -1c
.RI "struct \fBC13Parms\fP \fBC13\fP"
.br
.ti -1c
.RI "struct \fBSymbNFixationParms\fP \fBNFIX\fP"
.br
.ti -1c
.RI "struct \fBBioCroToCropcentParms\fP \fBbiocrotocentparms\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double ammonium"

.SS "double AWC"

.SS "struct \fBBioCroToCropcentParms\fP biocrotocentparms"

.SS "struct \fBC13Parms\fP C13"

.SS "double drainage"

.SS "struct \fBErosionParms\fP EROSION"

.SS "double leachedWATER"

.SS "double minK"

.SS "double minN"

.SS "double minP"

.SS "double minS"

.SS "double newminK"

.SS "double newminN"

.SS "double newminP"

.SS "double newminS"

.SS "struct \fBSymbNFixationParms\fP NFIX"

.SS "double nit_amt"

.SS "struct \fBOrgLeachParms\fP ORGLECH"

.SS "double PET"

.SS "double pH"

.SS "double soilrad"

.SS "double soilRELWC"

.SS "double soilTEMP"

.SS "struct \fBSoilTexture\fP SOILTEX"

.SS "double surfaceRELWC"

.SS "double surfaceTEMP"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
