.TH "DailyAutoResp" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DailyAutoResp \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBleafdarkresp\fP"
.br
.ti -1c
.RI "double \fBstemgrowth\fP"
.br
.ti -1c
.RI "double \fBrootgrowth\fP"
.br
.ti -1c
.RI "double \fBrhizomegrowth\fP"
.br
.ti -1c
.RI "double \fBstemmaint\fP"
.br
.ti -1c
.RI "double \fBrootmaint\fP"
.br
.ti -1c
.RI "double \fBrhizomemaint\fP"
.br
.ti -1c
.RI "double \fBtotal\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double leafdarkresp"

.SS "double rhizomegrowth"

.SS "double rhizomemaint"

.SS "double rootgrowth"

.SS "double rootmaint"

.SS "double stemgrowth"

.SS "double stemmaint"

.SS "double total"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
