.TH "dailyclimate" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dailyclimate \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdoy\fP"
.br
.ti -1c
.RI "double \fBtemp\fP"
.br
.ti -1c
.RI "double \fBprecip\fP"
.br
.ti -1c
.RI "double \fBsolar\fP"
.br
.ti -1c
.RI "double \fBwindspeed\fP"
.br
.ti -1c
.RI "double \fBrh\fP"
.br
.ti -1c
.RI "double \fBminimumTemp\fP"
.br
.ti -1c
.RI "double \fBsnow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "int doy"

.SS "double minimumTemp"

.SS "double precip"

.SS "double rh"

.SS "double snow"

.SS "double solar"

.SS "double temp"

.SS "double windspeed"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
