.TH "dbp_sugarcane_str" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dbp_sugarcane_str \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AuxcaneGro\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBkLeaf\fP"
.br
.ti -1c
.RI "double \fBkStem\fP"
.br
.ti -1c
.RI "double \fBkRoot\fP"
.br
.ti -1c
.RI "double \fBkSeedcane\fP"
.br
.ti -1c
.RI "double \fBkSugar\fP"
.br
.ti -1c
.RI "double \fBkFiber\fP"
.br
.ti -1c
.RI "double \fBkTassel\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double kFiber"

.SS "double kLeaf"

.SS "double kRoot"

.SS "double kSeedcane"

.SS "double kStem"

.SS "double kSugar"

.SS "double kTassel"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
