.TH "ErosionParms" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ErosionParms \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBLHZF\fP [3]"
.br
.ti -1c
.RI "double \fBEDEPTH\fP"
.br
.ti -1c
.RI "double \fBENRICH\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double EDEPTH"

.SS "double ENRICH"

.SS "double LHZF[3]"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
