.TH "ET_Str" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ET_Str \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AuxBioCro\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBTransR\fP"
.br
.ti -1c
.RI "double \fBEPenman\fP"
.br
.ti -1c
.RI "double \fBEPriestly\fP"
.br
.ti -1c
.RI "double \fBDeltat\fP"
.br
.ti -1c
.RI "double \fBLayerCond\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double Deltat"

.SS "double EPenman"

.SS "double EPriestly"

.SS "double LayerCond"

.SS "double TransR"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
