.TH "FILES_S" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FILES_S \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <soilwater\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBwbname\fP [\fBFILEPATH_MAX\fP]"
.br
.ti -1c
.RI "FILE * \fBfp_outf\fP"
.br
.ti -1c
.RI "FILE * \fBfp_soiln\fP"
.br
.ti -1c
.RI "FILE * \fBfp_co2\fP"
.br
.ti -1c
.RI "FILE * \fBfp_yearsum\fP"
.br
.ti -1c
.RI "FILE * \fBfp_soilc\fP"
.br
.ti -1c
.RI "FILE * \fBfp_tgmonth\fP"
.br
.ti -1c
.RI "FILE * \fBfp_dN2lyr\fP"
.br
.ti -1c
.RI "FILE * \fBfp_dN2Olyr\fP"
.br
.ti -1c
.RI "FILE * \fBfp_cflows\fP"
.br
.ti -1c
.RI "FILE * \fBfp_yrcflows\fP"
.br
.ti -1c
.RI "int \fBwrite_wb\fP"
.br
.ti -1c
.RI "int \fBwrite_co2\fP"
.br
.ti -1c
.RI "int \fBwrite_soiln\fP"
.br
.ti -1c
.RI "int \fBwrite_swc\fP"
.br
.ti -1c
.RI "int \fBwrite_wfps\fP"
.br
.ti -1c
.RI "int \fBwrite_soiltavg\fP"
.br
.ti -1c
.RI "int \fBwrite_soiltmin\fP"
.br
.ti -1c
.RI "int \fBwrite_soiltmax\fP"
.br
.ti -1c
.RI "int \fBwrite_stempdx\fP"
.br
.ti -1c
.RI "int \fBwrite_bio\fP"
.br
.ti -1c
.RI "int \fBwrite_wflux\fP"
.br
.ti -1c
.RI "int \fBwrite_mresp\fP"
.br
.ti -1c
.RI "int \fBwrite_yearsum\fP"
.br
.ti -1c
.RI "int \fBwrite_livec\fP"
.br
.ti -1c
.RI "int \fBwrite_deadc\fP"
.br
.ti -1c
.RI "int \fBwrite_soilc\fP"
.br
.ti -1c
.RI "int \fBwrite_sysc\fP"
.br
.ti -1c
.RI "int \fBwrite_tgmonth\fP"
.br
.ti -1c
.RI "int \fBwrite_dN2lyr\fP"
.br
.ti -1c
.RI "int \fBwrite_dN2Olyr\fP"
.br
.ti -1c
.RI "int \fBwrite_gresp\fP"
.br
.ti -1c
.RI "int \fBwrite_dels\fP"
.br
.ti -1c
.RI "int \fBwrite_dcsip\fP"
.br
.ti -1c
.RI "int \fBwrite_harvest\fP"
.br
.ti -1c
.RI "int \fBwrite_cflows\fP"
.br
.ti -1c
.RI "int \fBwrite_yrcflows\fP"
.br
.ti -1c
.RI "int \fBwrite_psyn\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "FILE* fp_cflows"

.SS "FILE* fp_co2"

.SS "FILE* fp_dN2lyr"

.SS "FILE* fp_dN2Olyr"

.SS "FILE* fp_outf"

.SS "FILE* fp_soilc"

.SS "FILE* fp_soiln"

.SS "FILE* fp_tgmonth"

.SS "FILE* fp_yearsum"

.SS "FILE* fp_yrcflows"

.SS "char wbname[\fBFILEPATH_MAX\fP]"

.SS "int write_bio"

.SS "int write_cflows"

.SS "int write_co2"

.SS "int write_dcsip"

.SS "int write_deadc"

.SS "int write_dels"

.SS "int write_dN2lyr"

.SS "int write_dN2Olyr"

.SS "int write_gresp"

.SS "int write_harvest"

.SS "int write_livec"

.SS "int write_mresp"

.SS "int write_psyn"

.SS "int write_soilc"

.SS "int write_soiln"

.SS "int write_soiltavg"

.SS "int write_soiltmax"

.SS "int write_soiltmin"

.SS "int write_stempdx"

.SS "int write_swc"

.SS "int write_sysc"

.SS "int write_tgmonth"

.SS "int write_wb"
! FILE *fp_snow; 
.SS "int write_wflux"

.SS "int write_wfps"

.SS "int write_yearsum"

.SS "int write_yrcflows"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
