.TH "FLAG_S" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FLAG_S \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <soilwater\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBverbose\fP"
.br
.ti -1c
.RI "int \fBdebug\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "int debug"

.SS "int verbose"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
