.TH "flow_str" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
flow_str \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Century\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBSC\fP"
.br
.ti -1c
.RI "double \fBfC\fP"
.br
.ti -1c
.RI "double \fBResp\fP"
.br
.ti -1c
.RI "double \fBMinN\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double fC"

.SS "double MinN"

.SS "double Resp"

.SS "double SC"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
