.TH "flowrestriction" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
flowrestriction \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBmaxCN\fP"
.br
.ti -1c
.RI "double \fBmaxCP\fP"
.br
.ti -1c
.RI "double \fBmaxCS\fP"
.br
.ti -1c
.RI "double \fBmaxCK\fP"
.br
.ti -1c
.RI "double \fBminCN\fP"
.br
.ti -1c
.RI "double \fBminCP\fP"
.br
.ti -1c
.RI "double \fBminCS\fP"
.br
.ti -1c
.RI "double \fBminCK\fP"
.br
.ti -1c
.RI "double \fBminN\fP"
.br
.ti -1c
.RI "double \fBminP\fP"
.br
.ti -1c
.RI "double \fBminS\fP"
.br
.ti -1c
.RI "double \fBminK\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double maxCK"

.SS "double maxCN"

.SS "double maxCP"

.SS "double maxCS"

.SS "double minCK"

.SS "double minCN"

.SS "double minCP"

.SS "double minCS"

.SS "double minK"

.SS "double minN"

.SS "double minP"

.SS "double minS"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
