.TH "harvesting::input" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
harvesting::input \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <management\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnumberofharvest\fP"
.br
.ti -1c
.RI "double * \fBdayofyear\fP"
.br
.ti -1c
.RI "double * \fBstemfractionleft\fP"
.br
.ti -1c
.RI "double * \fBleaffractionleft\fP"
.br
.ti -1c
.RI "double * \fBstemlitterleft\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double* dayofyear"

.SS "double* leaffractionleft"

.SS "int numberofharvest"

.SS "double* stemfractionleft"

.SS "double* stemlitterleft"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
