.TH "harvesting::output" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
harvesting::output \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <management\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double * \fBstem\fP"
.br
.ti -1c
.RI "double * \fBleaf\fP"
.br
.ti -1c
.RI "double * \fBrhizome\fP"
.br
.ti -1c
.RI "double * \fBroot\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double* \fBleaf\fP"

.SS "double* \fBrhizome\fP"

.SS "double* \fBroot\fP"

.SS "double* \fBstem\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
