.TH "LAYERPAR_S" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LAYERPAR_S \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <soilwater\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBwidth\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBdepth\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBdpthmn\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBdpthmx\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBbulkd\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBfieldc\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBwiltpt\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBecoeff\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBtcoeff\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBsandfrac\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBclayfrac\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBorgfrac\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBswclimit\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBsatcond\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBpH\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "int \fBnumlyrs\fP"
.br
.ti -1c
.RI "double \fBswcfc\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBswcwp\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBswc\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBswcmin\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBminpot\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBwfps\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBsumecoeff\fP"
.br
.ti -1c
.RI "int \fBnelyrs\fP"
.br
.ti -1c
.RI "double \fBthetas\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBthetas_bd\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBpsis\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBb\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "double \fBbinverse\fP [\fBMAXLYR\fP]"
.br
.ti -1c
.RI "int \fBubnd\fP [\fBCENTMAXLYR\fP]"
.br
.ti -1c
.RI "int \fBlbnd\fP [\fBCENTMAXLYR\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double b[\fBMAXLYR\fP]"

.SS "double binverse[\fBMAXLYR\fP]"

.SS "double bulkd[\fBMAXLYR\fP]"

.SS "double clayfrac[\fBMAXLYR\fP]"

.SS "double depth[\fBMAXLYR\fP]"

.SS "double dpthmn[\fBMAXLYR\fP]"

.SS "double dpthmx[\fBMAXLYR\fP]"

.SS "double ecoeff[\fBMAXLYR\fP]"

.SS "double fieldc[\fBMAXLYR\fP]"

.SS "int lbnd[\fBCENTMAXLYR\fP]"

.SS "double minpot[\fBMAXLYR\fP]"

.SS "int nelyrs"

.SS "int numlyrs"

.SS "double orgfrac[\fBMAXLYR\fP]"

.SS "double pH[\fBMAXLYR\fP]"

.SS "double psis[\fBMAXLYR\fP]"

.SS "double sandfrac[\fBMAXLYR\fP]"

.SS "double satcond[\fBMAXLYR\fP]"

.SS "double sumecoeff"

.SS "double swc[\fBMAXLYR\fP]"

.SS "double swcfc[\fBMAXLYR\fP]"

.SS "double swclimit[\fBMAXLYR\fP]"

.SS "double swcmin[\fBMAXLYR\fP]"

.SS "double swcwp[\fBMAXLYR\fP]"

.SS "double tcoeff[\fBMAXLYR\fP]"

.SS "double thetas[\fBMAXLYR\fP]"

.SS "double thetas_bd[\fBMAXLYR\fP]"

.SS "int ubnd[\fBCENTMAXLYR\fP]"

.SS "double wfps[\fBMAXLYR\fP]"

.SS "double width[\fBMAXLYR\fP]"

.SS "double wiltpt[\fBMAXLYR\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
