.TH "leaf" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
leaf \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBbiomass\fP"
.br
.ti -1c
.RI "double \fBlitter\fP"
.br
.ti -1c
.RI "struct \fBminerals\fP biomassE \fBlitterE\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double biomass"

.SS "double litter"

.SS "struct \fBminerals\fP biomassE litterE"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
