.TH "littervec" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
littervec \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBbiomass\fP"
.br
.ti -1c
.RI "double \fBageinTT\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double ageinTT"

.SS "double biomass"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
