.TH "management" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
management \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBemergenceparms\fP"
.br
.ti -1c
.RI "struct \fBharvestparms\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBmanagement::harvestparms\fP \fBharvestparms\fP"
.br
.ti -1c
.RI "struct \fBmanagement::emergenceparms\fP \fBemergenceparms\fP"
.br
.ti -1c
.RI "struct \fBplanting\fP \fBplanting\fP"
.br
.ti -1c
.RI "struct \fBharvesting\fP \fBharvesting\fP"
.br
.ti -1c
.RI "struct \fBNapplication\fP \fBNapplication\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "struct \fBmanagement::emergenceparms\fP \fBemergenceparms\fP"

.SS "struct \fBharvesting\fP \fBharvesting\fP"

.SS "struct \fBmanagement::harvestparms\fP \fBharvestparms\fP"

.SS "struct \fBNapplication\fP \fBNapplication\fP"

.SS "struct \fBplanting\fP \fBplanting\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
