.TH "management::harvestparms" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
management::harvestparms \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBharvestdoy\fP"
.br
.ti -1c
.RI "double \fBfrleaf\fP"
.br
.ti -1c
.RI "double \fBfrleaflitter\fP"
.br
.ti -1c
.RI "double \fBfrstem\fP"
.br
.ti -1c
.RI "double \fBfrstemlitter\fP"
.br
.ti -1c
.RI "double \fBfrdeadroot\fP"
.br
.ti -1c
.RI "double \fBfrdeadrhizome\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double frdeadrhizome"

.SS "double frdeadroot"

.SS "double frleaf"

.SS "double frleaflitter"

.SS "double frstem"

.SS "double frstemlitter"

.SS "int harvestdoy"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
