.TH "metabc1::Flux6" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
metabc1::Flux6 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBflow\fP \fBmetabc1TOsom1c1\fP"
.br
.ti -1c
.RI "struct \fBflow\fP \fBmetabc1TOmetabc1\fP"
.br
.ti -1c
.RI "double \fBhetresp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double hetresp"

.SS "struct \fBflow\fP metabc1TOmetabc1"

.SS "struct \fBflow\fP metabc1TOsom1c1"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
