.TH "metabc2::Flux7" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
metabc2::Flux7 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBflow\fP \fBmetabc2TOsom1c2\fP"
.br
.ti -1c
.RI "struct \fBflow\fP \fBmetabc2TOmetabc2\fP"
.br
.ti -1c
.RI "double \fBhetresp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double hetresp"

.SS "struct \fBflow\fP metabc2TOmetabc2"

.SS "struct \fBflow\fP metabc2TOsom1c2"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
