.TH "miscanthus" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
miscanthus \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBleaf\fP \fBleaf\fP"
.br
.ti -1c
.RI "struct \fBstem\fP \fBstem\fP"
.br
.ti -1c
.RI "struct \fBrhizome\fP \fBrhizome\fP"
.br
.ti -1c
.RI "struct \fBroot\fP \fBroot\fP"
.br
.ti -1c
.RI "struct \fBdailyvec\fP * \fBleafvec\fP"
.br
.ti -1c
.RI "struct \fBdailyvec\fP * \fBstemvec\fP"
.br
.ti -1c
.RI "struct \fBdailyvec\fP * \fBrootvec\fP"
.br
.ti -1c
.RI "struct \fBdailyvec\fP * \fBrhizomevec\fP"
.br
.ti -1c
.RI "struct \fBDailyAutoResp\fP \fBautoresp\fP"
.br
.ti -1c
.RI "double \fBGPP\fP"
.br
.ti -1c
.RI "double \fBNPP\fP"
.br
.ti -1c
.RI "double \fBLAI\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "struct \fBDailyAutoResp\fP autoresp"

.SS "double GPP"

.SS "double LAI"

.SS "struct \fBleaf\fP \fBleaf\fP"

.SS "struct \fBdailyvec\fP* leafvec"

.SS "double NPP"

.SS "struct \fBrhizome\fP \fBrhizome\fP"

.SS "struct \fBdailyvec\fP * rhizomevec"

.SS "struct \fBroot\fP \fBroot\fP"

.SS "struct \fBdailyvec\fP * rootvec"

.SS "struct \fBstem\fP \fBstem\fP"

.SS "struct \fBdailyvec\fP * stemvec"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
