.TH "Napplication" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Napplication \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <management\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnumberofNapplication\fP"
.br
.ti -1c
.RI "double * \fBdayofyear\fP"
.br
.ti -1c
.RI "double \fBrate\fP"
.br
.ti -1c
.RI "char \fBmethod\fP"
.br
.ti -1c
.RI "char \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double* dayofyear"

.SS "char method"

.SS "int numberofNapplication"

.SS "double rate"

.SS "char type"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
