.TH "nitroParms" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
nitroParms \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AuxBioCro\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBileafN\fP"
.br
.ti -1c
.RI "double \fBkln\fP"
.br
.ti -1c
.RI "double \fBVmaxb1\fP"
.br
.ti -1c
.RI "double \fBVmaxb0\fP"
.br
.ti -1c
.RI "double \fBalphab1\fP"
.br
.ti -1c
.RI "double \fBalphab0\fP"
.br
.ti -1c
.RI "double \fBRdb1\fP"
.br
.ti -1c
.RI "double \fBRdb0\fP"
.br
.ti -1c
.RI "double \fBkpLN\fP"
.br
.ti -1c
.RI "double \fBlnb0\fP"
.br
.ti -1c
.RI "double \fBlnb1\fP"
.br
.ti -1c
.RI "int \fBlnFun\fP"
.br
.ti -1c
.RI "double \fBmaxln\fP"
.br
.ti -1c
.RI "double \fBminln\fP"
.br
.ti -1c
.RI "double \fBdaymaxln\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double alphab0"

.SS "double alphab1"

.SS "double daymaxln"

.SS "double ileafN"

.SS "double kln"

.SS "double kpLN"

.SS "double lnb0"

.SS "double lnb1"

.SS "int lnFun"

.SS "double maxln"

.SS "double minln"

.SS "double Rdb0"

.SS "double Rdb1"

.SS "double Vmaxb0"

.SS "double Vmaxb1"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
