.TH "OrgLeachParms" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OrgLeachParms \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBDailyThresholdFlow\fP"
.br
.ti -1c
.RI "double \fBOMLEACH\fP [3]"
.br
.ti -1c
.RI "struct \fBminerals\fP \fBsom1c2toleach\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double DailyThresholdFlow"

.SS "double OMLEACH[3]"

.SS "struct \fBminerals\fP som1c2toleach"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
