.TH "senthermaltemp" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
senthermaltemp \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBleafcriticalT\fP"
.br
.ti -1c
.RI "double \fBleaffr\fP"
.br
.ti -1c
.RI "double \fBstemcriticalT\fP"
.br
.ti -1c
.RI "double \fBstemfr\fP"
.br
.ti -1c
.RI "double \fBrhizomecriticalT\fP"
.br
.ti -1c
.RI "double \fBrhizomefr\fP"
.br
.ti -1c
.RI "double \fBrootcriticalT\fP"
.br
.ti -1c
.RI "double \fBrootfr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double leafcriticalT"

.SS "double leaffr"

.SS "double rhizomecriticalT"

.SS "double rhizomefr"

.SS "double rootcriticalT"

.SS "double rootfr"

.SS "double stemcriticalT"

.SS "double stemfr"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
