.TH "SITEPAR_S" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SITEPAR_S \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <soilwater\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBusexdrvrs\fP"
.br
.ti -1c
.RI "double \fBsublimscale\fP"
.br
.ti -1c
.RI "double \fBreflec\fP"
.br
.ti -1c
.RI "double \fBalbedo\fP"
.br
.ti -1c
.RI "double \fBfswcinit\fP"
.br
.ti -1c
.RI "double \fBdmpflux\fP"
.br
.ti -1c
.RI "double \fBhours_rain\fP"
.br
.ti -1c
.RI "int \fBwatertable\fP [\fBNMONTH\fP+1]"
.br
.ti -1c
.RI "double \fBhpotdeep\fP"
.br
.ti -1c
.RI "double \fBksatdeep\fP"
.br
.ti -1c
.RI "double \fBrlatitude\fP"
.br
.ti -1c
.RI "double \fBcldcov\fP [\fBNMONTH\fP+1]"
.br
.ti -1c
.RI "int \fBtexture\fP"
.br
.ti -1c
.RI "double \fBtbotmn\fP"
.br
.ti -1c
.RI "double \fBtbotmx\fP"
.br
.ti -1c
.RI "double \fBdmp\fP"
.br
.ti -1c
.RI "double \fBtimlag\fP"
.br
.ti -1c
.RI "double \fBNcoeff\fP"
.br
.ti -1c
.RI "int \fBdrainlag\fP"
.br
.ti -1c
.RI "int \fBjdayStart\fP"
.br
.ti -1c
.RI "int \fBjdayEnd\fP"
.br
.ti -1c
.RI "double \fBN2Oadjust\fP"
.br
.ti -1c
.RI "double \fBelevation\fP"
.br
.ti -1c
.RI "double \fBslope\fP"
.br
.ti -1c
.RI "double \fBaspect\fP"
.br
.ti -1c
.RI "double \fBehoriz\fP"
.br
.ti -1c
.RI "double \fBwhoriz\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double albedo"

.SS "double aspect"

.SS "double cldcov[\fBNMONTH\fP+1]"

.SS "double dmp"

.SS "double dmpflux"

.SS "int drainlag"

.SS "double ehoriz"

.SS "double elevation"

.SS "double fswcinit"

.SS "double hours_rain"

.SS "double hpotdeep"

.SS "int jdayEnd"

.SS "int jdayStart"

.SS "double ksatdeep"

.SS "double N2Oadjust"

.SS "double Ncoeff"

.SS "double reflec"

.SS "double rlatitude"

.SS "double slope"

.SS "double sublimscale"

.SS "double tbotmn"

.SS "double tbotmx"

.SS "int texture"

.SS "double timlag"

.SS "int usexdrvrs"

.SS "int watertable[\fBNMONTH\fP+1]"

.SS "double whoriz"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
