.TH "siteparameters" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
siteparameters \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBNcoeff\fP"
.br
.ti -1c
.RI "double \fBjdayStart\fP"
.br
.ti -1c
.RI "double \fBjdayEnd\fP"
.br
.ti -1c
.RI "double \fBN2Oadjust\fP"
.br
.ti -1c
.RI "int \fBisagri\fP"
.br
.ti -1c
.RI "int \fBisdecid\fP"
.br
.ti -1c
.RI "int \fBmaxt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "int isagri"

.SS "int isdecid"

.SS "double jdayEnd"

.SS "double jdayStart"

.SS "int maxt"

.SS "double N2Oadjust"

.SS "double Ncoeff"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
