.TH "soilML_str" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
soilML_str \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AuxBioCro\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBrcoefPhoto\fP"
.br
.ti -1c
.RI "double \fBrcoefSpleaf\fP"
.br
.ti -1c
.RI "double \fBcws\fP [\fBMAXLAY\fP]"
.br
.ti -1c
.RI "double \fBdrainage\fP"
.br
.ti -1c
.RI "double \fBNleach\fP"
.br
.ti -1c
.RI "double \fBSoilEvapo\fP"
.br
.ti -1c
.RI "double \fBrootDist\fP [\fBMAXLAY\fP]"
.br
.ti -1c
.RI "double \fBhourlyWflux\fP [\fBMAXLAY\fP]"
.br
.ti -1c
.RI "double \fBdailyWflux\fP [\fBMAXLAY\fP]"
.br
.ti -1c
.RI "double \fBwidth\fP [\fBMAXLAY\fP]"
.br
.ti -1c
.RI "double \fBswclimit\fP [\fBMAXLAY\fP]"
.br
.ti -1c
.RI "double \fBpH\fP [\fBMAXLAY\fP]"
.br
.ti -1c
.RI "double \fBbulkd\fP [\fBMAXLAY\fP]"
.br
.ti -1c
.RI "double \fBfieldc\fP [\fBMAXLAY\fP]"
.br
.ti -1c
.RI "double \fBdpthmx\fP [\fBMAXLAY\fP]"
.br
.ti -1c
.RI "double \fBdpthmn\fP [\fBMAXLAY\fP]"
.br
.ti -1c
.RI "double \fBsoiltavg\fP [\fBMAXLAY\fP]"
.br
.ti -1c
.RI "double \fBsand\fP [\fBMAXLAY\fP]"
.br
.ti -1c
.RI "double \fBsilt\fP [\fBMAXLAY\fP]"
.br
.ti -1c
.RI "double \fBclay\fP [\fBMAXLAY\fP]"
.br
.ti -1c
.RI "int \fBNum_BioCro_soil_layers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double bulkd[\fBMAXLAY\fP]"

.SS "double clay[\fBMAXLAY\fP]"

.SS "double cws[\fBMAXLAY\fP]"

.SS "double dailyWflux[\fBMAXLAY\fP]"

.SS "double dpthmn[\fBMAXLAY\fP]"

.SS "double dpthmx[\fBMAXLAY\fP]"

.SS "double drainage"

.SS "double fieldc[\fBMAXLAY\fP]"

.SS "double hourlyWflux[\fBMAXLAY\fP]"

.SS "double Nleach"

.SS "int Num_BioCro_soil_layers"

.SS "double pH[\fBMAXLAY\fP]"

.SS "double rcoefPhoto"

.SS "double rcoefSpleaf"

.SS "double rootDist[\fBMAXLAY\fP]"

.SS "double sand[\fBMAXLAY\fP]"

.SS "double silt[\fBMAXLAY\fP]"

.SS "double SoilEvapo"

.SS "double soiltavg[\fBMAXLAY\fP]"

.SS "double swclimit[\fBMAXLAY\fP]"

.SS "double width[\fBMAXLAY\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
