.TH "soilText_str" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
soilText_str \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AuxBioCro\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBsilt\fP"
.br
.ti -1c
.RI "double \fBclay\fP"
.br
.ti -1c
.RI "double \fBsand\fP"
.br
.ti -1c
.RI "double \fBair_entry\fP"
.br
.ti -1c
.RI "double \fBb\fP"
.br
.ti -1c
.RI "double \fBKs\fP"
.br
.ti -1c
.RI "double \fBsatur\fP"
.br
.ti -1c
.RI "double \fBfieldc\fP"
.br
.ti -1c
.RI "double \fBwiltp\fP"
.br
.ti -1c
.RI "double \fBbulkd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double air_entry"

.SS "double b"

.SS "double bulkd"

.SS "double clay"

.SS "double fieldc"

.SS "double Ks"

.SS "double sand"

.SS "double satur"

.SS "double silt"

.SS "double wiltp"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
