.TH "soilprofile" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
soilprofile \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBprofilefluxes\fP"
.br
.ti -1c
.RI "struct \fBprofilepools\fP"
.br
.ti -1c
.RI "struct \fBprofileproperties\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnumber_layers\fP"
.br
.ti -1c
.RI "double \fBMAXdepth\fP"
.br
.ti -1c
.RI "double \fBCH4depth\fP"
.br
.ti -1c
.RI "double \fBSOCdepth\fP"
.br
.ti -1c
.RI "double \fBcritflow\fP"
.br
.ti -1c
.RI "struct 
.br
\fBsoilprofile::profileproperties\fP \fBproperties\fP"
.br
.ti -1c
.RI "struct \fBsoilprofile::profilepools\fP \fBpools\fP"
.br
.ti -1c
.RI "struct \fBsoilprofile::profilefluxes\fP \fBflux\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double CH4depth"

.SS "double critflow"

.SS "struct \fBsoilprofile::profilefluxes\fP flux"

.SS "double MAXdepth"

.SS "int number_layers"

.SS "struct \fBsoilprofile::profilepools\fP pools"

.SS "struct \fBsoilprofile::profileproperties\fP  properties"

.SS "double SOCdepth"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
