.TH "soilprofile::profilefluxes" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
soilprofile::profilefluxes \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBwaterflux\fP [\fBMAXSOILLAY\fP]"
.br
.ti -1c
.RI "double \fBdN2lyr\fP [\fBMAXSOILLAY\fP]"
.br
.ti -1c
.RI "double \fBdN2Olyr\fP [\fBMAXSOILLAY\fP]"
.br
.ti -1c
.RI "double \fBfrlechd\fP [\fBMAXSOILLAY\fP]"
.br
.ti -1c
.RI "double \fBstream\fP [\fBMAXSOILLAY\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double dN2lyr[\fBMAXSOILLAY\fP]"

.SS "double dN2Olyr[\fBMAXSOILLAY\fP]"

.SS "double frlechd[\fBMAXSOILLAY\fP]"

.SS "double stream[\fBMAXSOILLAY\fP]"

.SS "double waterflux[\fBMAXSOILLAY\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
