.TH "SoilTexture" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoilTexture \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBsand\fP"
.br
.ti -1c
.RI "double \fBsilt\fP"
.br
.ti -1c
.RI "double \fBclay\fP"
.br
.ti -1c
.RI "double \fBfieldc\fP"
.br
.ti -1c
.RI "double \fBbulkd\fP"
.br
.ti -1c
.RI "double \fBavgwfps\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double avgwfps"

.SS "double bulkd"

.SS "double clay"

.SS "double fieldc"

.SS "double sand"

.SS "double silt"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
