.TH "SoilWaterEffectParms" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SoilWaterEffectParms \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBa\fP"
.br
.ti -1c
.RI "double \fBb\fP"
.br
.ti -1c
.RI "double \fBc\fP"
.br
.ti -1c
.RI "double \fBd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double a"

.SS "double b"

.SS "double c"

.SS "double d"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
