.TH "soilprofile::profileproperties" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
soilprofile::profileproperties \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBbulkd\fP [\fBMAXSOILLAY\fP]"
.br
.ti -1c
.RI "double \fBfieldc\fP [\fBMAXSOILLAY\fP]"
.br
.ti -1c
.RI "double \fBpH\fP [\fBMAXSOILLAY\fP]"
.br
.ti -1c
.RI "double \fBswclimit\fP [\fBMAXSOILLAY\fP]"
.br
.ti -1c
.RI "double \fBsoiltavg\fP [\fBMAXSOILLAY\fP]"
.br
.ti -1c
.RI "double \fBdpthmn\fP [\fBMAXSOILLAY\fP]"
.br
.ti -1c
.RI "double \fBdpthmx\fP [\fBMAXSOILLAY\fP]"
.br
.ti -1c
.RI "double \fBwidth\fP [\fBMAXSOILLAY\fP]"
.br
.ti -1c
.RI "double \fBstream\fP [\fBMAXSOILLAY\fP]"
.br
.ti -1c
.RI "double \fBfrlechd\fP [\fBMAXSOILLAY\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double bulkd[\fBMAXSOILLAY\fP]"

.SS "double dpthmn[\fBMAXSOILLAY\fP]"

.SS "double dpthmx[\fBMAXSOILLAY\fP]"

.SS "double fieldc[\fBMAXSOILLAY\fP]"

.SS "double frlechd[\fBMAXSOILLAY\fP]"

.SS "double pH[\fBMAXSOILLAY\fP]"

.SS "double soiltavg[\fBMAXSOILLAY\fP]"

.SS "double stream[\fBMAXSOILLAY\fP]"

.SS "double swclimit[\fBMAXSOILLAY\fP]"

.SS "double width[\fBMAXSOILLAY\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
