.TH "soilprofile::profilepools" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
soilprofile::profilepools \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBswc\fP [\fBMAXSOILLAY\fP]"
.br
.ti -1c
.RI "double \fBrootbiomass\fP [\fBMAXSOILLAY\fP]"
.br
.ti -1c
.RI "double \fBwfps\fP [\fBMAXSOILLAY\fP]"
.br
.ti -1c
.RI "double \fBnitrate\fP [\fBMAXSOILLAY\fP]"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double nitrate[\fBMAXSOILLAY\fP]"

.SS "double rootbiomass[\fBMAXSOILLAY\fP]"

.SS "double swc[\fBMAXSOILLAY\fP]"

.SS "double wfps[\fBMAXSOILLAY\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
