.TH "som1c1::Flux8" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
som1c1::Flux8 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBflow\fP \fBsom1c1TOsom2c1\fP"
.br
.ti -1c
.RI "struct \fBflow\fP \fBsom1c1TOsom1c1\fP"
.br
.ti -1c
.RI "double \fBhetresp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double hetresp"

.SS "struct \fBflow\fP som1c1TOsom1c1"

.SS "struct \fBflow\fP som1c1TOsom2c1"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
