.TH "som1c2::parms10" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
som1c2::parms10 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBk\fP"
.br
.ti -1c
.RI "double \fBtimestep\fP"
.br
.ti -1c
.RI "double \fBpeftxa\fP"
.br
.ti -1c
.RI "double \fBpeftxb\fP"
.br
.ti -1c
.RI "double \fBp1co2a\fP"
.br
.ti -1c
.RI "double \fBp1co2b\fP"
.br
.ti -1c
.RI "double \fBps1s3\fP [2]"
.br
.ti -1c
.RI "double \fBanimpt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double animpt"

.SS "double k"

.SS "double p1co2a"

.SS "double p1co2b"

.SS "double peftxa"

.SS "double peftxb"

.SS "double ps1s3[2]"

.SS "double timestep"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
