.TH "som1c1::parms8" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
som1c1::parms8 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBk\fP"
.br
.ti -1c
.RI "double \fBtimestep\fP"
.br
.ti -1c
.RI "double \fBa\fP"
.br
.ti -1c
.RI "double \fBb\fP"
.br
.ti -1c
.RI "double \fBx1\fP"
.br
.ti -1c
.RI "double \fBx2\fP"
.br
.ti -1c
.RI "double \fBp1co2a\fP"
.br
.ti -1c
.RI "double \fBp1co2b\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double a"

.SS "double b"

.SS "double k"

.SS "double p1co2a"

.SS "double p1co2b"

.SS "double timestep"

.SS "double x1"

.SS "double x2"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
