.TH "som2c2" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
som2c2 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBFlux11\fP"
.br
.ti -1c
.RI "struct \fBparms11\fP"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBcarbon\fP \fBC\fP"
.br
.ti -1c
.RI "struct \fBminerals\fP \fBE\fP"
.br
.ti -1c
.RI "struct \fBsom2c2::Flux11\fP \fBFlux\fP"
.br
.ti -1c
.RI "struct \fBsom2c2::parms11\fP \fBparms\fP"
.br
.ti -1c
.RI "struct \fBTempEffectParms\fP \fBTEff\fP"
.br
.ti -1c
.RI "struct \fBSoilWaterEffectParms\fP \fBSWEFF\fP"
.br
.ti -1c
.RI "struct \fBAnaerobicParms\fP \fBANEREFF\fP"
.br
.ti -1c
.RI "struct \fBPHParms\fP \fBPHEFF\fP"
.br
.ti -1c
.RI "struct \fBflowrestriction\fP \fBINFLOW\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "struct \fBAnaerobicParms\fP ANEREFF"

.SS "struct \fBcarbon\fP C"

.SS "struct \fBminerals\fP E"

.SS "struct \fBsom2c2::Flux11\fP  Flux"

.SS "struct \fBflowrestriction\fP INFLOW"

.SS "struct \fBsom2c2::parms11\fP  parms"

.SS "struct \fBPHParms\fP PHEFF"

.SS "struct \fBSoilWaterEffectParms\fP SWEFF"

.SS "struct \fBTempEffectParms\fP TEff"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
