.TH "som2c2::parms11" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
som2c2::parms11 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBk\fP"
.br
.ti -1c
.RI "double \fBtimestep\fP"
.br
.ti -1c
.RI "double \fBp2co2\fP"
.br
.ti -1c
.RI "double \fBps2s3\fP [2]"
.br
.ti -1c
.RI "double \fBanimpt\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double animpt"

.SS "double k"

.SS "double p2co2"

.SS "double ps2s3[2]"

.SS "double timestep"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
