.TH "som2c1::parms9" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
som2c1::parms9 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBk\fP"
.br
.ti -1c
.RI "double \fBtimestep\fP"
.br
.ti -1c
.RI "double \fBa\fP"
.br
.ti -1c
.RI "double \fBb\fP"
.br
.ti -1c
.RI "double \fBx1\fP"
.br
.ti -1c
.RI "double \fBx2\fP"
.br
.ti -1c
.RI "double \fBp2co2\fP"
.br
.ti -1c
.RI "double \fBmix\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double a"

.SS "double b"

.SS "double k"

.SS "double mix"

.SS "double p2co2"

.SS "double timestep"

.SS "double x1"

.SS "double x2"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
