.TH "som3c::Flux12" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
som3c::Flux12 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBflow\fP \fBsom3cTOsom1c2\fP"
.br
.ti -1c
.RI "struct \fBflow\fP \fBsom3cTOsom3c\fP"
.br
.ti -1c
.RI "double \fBhetresp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double hetresp"

.SS "struct \fBflow\fP som3cTOsom1c2"

.SS "struct \fBflow\fP som3cTOsom3c"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
