.TH "/home/dlebauer/dev/biocro/src/swconst.h" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/dlebauer/dev/biocro/src/swconst.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSEC_PER_DAY\fP   86400"
.br
.ti -1c
.RI "#define \fBSEC_PER_HOUR\fP   3600"
.br
.ti -1c
.RI "#define \fBHOURS_PER_DAY\fP   24"
.br
.ti -1c
.RI "#define \fBNDAY\fP   366               /* dimension for daily arrays */"
.br
.ti -1c
.RI "#define \fBNMONTH\fP   12              /* # of months in a year */"
.br
.ti -1c
.RI "#define \fBMAXLYR\fP   200              /* Max # of soil layers (soil water model) */"
.br
.ti -1c
.RI "#define \fBCENTMAXLYR\fP   10          /* Max # of century soil layers */"
.br
.ti -1c
.RI "#define \fBMAXSTLYR\fP   200           /* Max # of soil temperature layers */"
.br
.ti -1c
.RI "#define \fBPARTDENS\fP   2\&.65          /* Particle Density (g/cm3) */"
.br
.ti -1c
.RI "#define \fBPI\fP   3\&.14159265"
.br
.ti -1c
.RI "#define \fBCONVLAI\fP   80    /* biomass needed to produce an LAI of 1 (g/m**2) */"
.br
.ti -1c
.RI "#define \fBFNSOIL\fP   'soils\&.in'"
.br
.ti -1c
.RI "#define \fBFNSITE\fP   'sitepar\&.in'"
.br
.ti -1c
.RI "#define \fBmax\fP(a, b)   (((a) > (b)) ? (a) : (b))"
.br
.ti -1c
.RI "#define \fBmin\fP(a, b)   (((a) < (b)) ? (a) : (b))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CENTMAXLYR   10          /* Max # of century soil layers */"

.SS "#define CONVLAI   80    /* biomass needed to produce an LAI of 1 (g/m**2) */"

.SS "#define FNSITE   'sitepar\&.in'"

.SS "#define FNSOIL   'soils\&.in'"

.SS "#define HOURS_PER_DAY   24"

.SS "#define max(a, b)   (((a) > (b)) ? (a) : (b))"

.SS "#define MAXLYR   200              /* Max # of soil layers (soil water model) */"

.SS "#define MAXSTLYR   200           /* Max # of soil temperature layers */"

.SS "#define min(a, b)   (((a) < (b)) ? (a) : (b))"

.SS "#define NDAY   366               /* dimension for daily arrays */"

.SS "#define NMONTH   12              /* # of months in a year */"

.SS "#define PARTDENS   2\&.65          /* Particle Density (g/cm3) */"

.SS "#define PI   3\&.14159265"

.SS "#define SEC_PER_DAY   86400"

.SS "#define SEC_PER_HOUR   3600"

.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
