.TH "SymbNFixationParms" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SymbNFixationParms \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBFXMCA\fP"
.br
.ti -1c
.RI "double \fBFXMCB\fP"
.br
.ti -1c
.RI "double \fBFXMXS\fP"
.br
.ti -1c
.RI "double \fBFXNPB\fP"
.br
.ti -1c
.RI "int \fBNSNFIX\fP"
.br
.RI "\fIContrl of P on non-symbiotic fixation rate on availability of top soil N rate when NSNFIX=1\&.0\&. \fP"
.ti -1c
.RI "double \fBNTSPM\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double FXMCA"

.SS "double FXMCB"

.SS "double FXMXS"

.SS "double FXNPB"

.SS "int NSNFIX"

.PP
Contrl of P on non-symbiotic fixation rate on availability of top soil N rate when NSNFIX=1\&.0\&. 
.SS "double NTSPM"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
