.TH "TempEffectParms" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TempEffectParms \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBteff1\fP"
.br
.ti -1c
.RI "double \fBteff2\fP"
.br
.ti -1c
.RI "double \fBteff3\fP"
.br
.ti -1c
.RI "double \fBteff4\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double teff1"

.SS "double teff2"

.SS "double teff3"

.SS "double teff4"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
