.TH "wood3::parms5" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wood3::parms5 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crocent\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBk\fP"
.br
.ti -1c
.RI "double \fBtimestep\fP"
.br
.ti -1c
.RI "double \fBpligst\fP"
.br
.ti -1c
.RI "double \fBrsplig\fP"
.br
.ti -1c
.RI "double \fBps1co2\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double k"

.SS "double pligst"

.SS "double ps1co2"

.SS "double rsplig"

.SS "double timestep"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
