.TH "ws_str" 3 "Fri Apr 3 2015" "Version 0.92" "BioCro" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ws_str \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <AuxBioCro\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "double \fBrcoefPhoto\fP"
.br
.ti -1c
.RI "double \fBrcoefSpleaf\fP"
.br
.ti -1c
.RI "double \fBawc\fP"
.br
.ti -1c
.RI "double \fBpsim\fP"
.br
.ti -1c
.RI "double \fBrunoff\fP"
.br
.ti -1c
.RI "double \fBNleach\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
.SH "Field Documentation"
.PP 
.SS "double awc"

.SS "double Nleach"

.SS "double psim"

.SS "double rcoefPhoto"

.SS "double rcoefSpleaf"

.SS "double runoff"


.SH "Author"
.PP 
Generated automatically by Doxygen for BioCro from the source code\&.
